[package]
name = "py-rust-module"
version = "0.1.0"
edition = "2021"

[lib]
name = "py_rust_module"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.28.2"
pyo3-stub-gen = "0.19.0"
serde = "1.0.228"
serde_json = "1.0.149"
